#!/bin/bash

main() {
    # Set shell options
    set -eu

    # Get build args
    TEMPLATE=$1
    VARS=$2
    README_J2="${3:-}"

    # Define build vars
    START_EPOCH=$(date +%s)
    TIMESTAMP=$(date -d @${START_EPOCH} +"%Y%m%d_%H%M%S")
    # One idea for build tag is epoch in hex, but not sure yet if it is
    # just unnecessary mental acrobatics.
    #
    # BUILD_TAG=$(printf "%x" ${START_EPOCH})
    #
    BUILD_TAG=$TIMESTAMP
    NAME=$(scripts/render-recipe $BUILD_TAG $TEMPLATE $VARS | yq . | jq -r '.name')

    # Define build paths
    build_dir="builds/$NAME-${TIMESTAMP}"
    recipe_file="$build_dir/$NAME-${TIMESTAMP}.yaml"
    build_log="$build_dir/$NAME-${TIMESTAMP}.log"

    # Make build directory
    mkdir $build_dir

    # Log recipe template
    echo "$(date +'%Y%m%d %H:%M:%S') starting build with tag $BUILD_TAG" | tee -a $build_log
    echo "$(date +'%Y%m%d %H:%M:%S') generating build recipe from template" | tee -a $build_log
    echo "$(date +'%Y%m%d %H:%M:%S') template $TEMPLATE:" | tee -a $build_log
    cat $TEMPLATE | tee -a $build_log
    echo | tee -a $build_log

    # Log recipe vars
    echo "$(date +'%Y%m%d %H:%M:%S') vars $VARS:" | tee -a $build_log
    cat $VARS| tee -a $build_log
    echo | tee -a $build_log

    # Generate build recipe
    scripts/render-recipe $BUILD_TAG $TEMPLATE $VARS | tee $recipe_file

    if [[ -n "$README_J2" ]]; then
        readme_file="$build_dir/$NAME-${TIMESTAMP}.md"
	scripts/j2render "$README_J2" "$recipe_file"  | tee "$readme_file"
    fi

    # Log generated recipe
    echo "$(date +'%Y%m%d %H:%M:%S'): generated recipe $recipe_file:" | tee -a $build_log
    cat $recipe_file | tee -a $build_log

    # Log git status
    echo "$(date +'%Y%m%d %H:%M:%S'): git working dir status:" | tee -a $build_log
    echo "Git commit: $(git rev-parse --short HEAD)" | tee -a $build_log
    echo "Modified files: $(git status --porcelain)" | tee -a $build_log
    echo "Git diff:" | tee -a $build_log
    git diff | tee -a $build_log

    # Build container image from recipe
    echo "$(date +'%Y%m%d %H:%M:%S'): starting build" | tee -a $build_log
    scripts/build-images build $recipe_file  $build_dir | tee -a $build_log
    echo "$(date +'%Y%m%d %H:%M:%S'): build completed" | tee -a $build_log
}

main "$@"
