#!/bin/bash

main() {
    # Set shell options
    set -eu

    # Get build args
    TEMPLATE=$1
    VARS=$2
    README_J2="${3:-}"

    # Define build vars
    START_EPOCH=$(date +%s)
    TIMESTAMP=$(date -d @${START_EPOCH} +"%Y%m%d_%H%M%S")
    # One idea for build tag is epoch in hex, but not sure yet if it is
    # just unnecessary mental acrobatics.
    #
    # BUILD_TAG=$(printf "%x" ${START_EPOCH})
    #
    BUILD_TAG=$TIMESTAMP
    NAME=$(scripts/render-recipe $BUILD_TAG $TEMPLATE $VARS | yq . | jq -r '.name')

    # Define build paths
    build_dir="builds/$NAME-${TIMESTAMP}"
    recipe_file="$build_dir/$NAME-${TIMESTAMP}.yaml"
    build_log="$build_dir/$NAME-${TIMESTAMP}.log"

    # Create build directory and recipe directory under it
    mkdir $build_dir

    # Log BUILD_TAG, TEMPLATE and VAR as well as git working directory status
    echo "$(date +'%Y%m%d %H:%M:%S') starting build with tag $BUILD_TAG for recipe $NAME" | tee -a $build_log
    echo "$(date +'%Y%m%d %H:%M:%S') git working dir status:" | tee -a $build_log
    echo "git commit: $(git rev-parse --short HEAD)" | sed 's/^/    /' | tee -a $build_log
    echo "modified files: $(git status --porcelain | xargs echo)" | sed 's/^/    /' | tee -a $build_log
    echo "git diff:" | sed 's/^/    /' | tee -a $build_log
    git diff | sed 's/^/        /' | tee -a $build_log

    echo "$(date +'%Y%m%d %H:%M:%S') generating recipe from template and vars file" | tee -a $build_log
    scripts/render-recipe $BUILD_TAG $TEMPLATE $VARS $README_J2 > $recipe_file

    echo "$(date +'%Y%m%d %H:%M:%S') sha256 sums for the template, vars and final recipe are:" | tee -a $build_log
    sha256sum $TEMPLATE $VARS $recipe_file | sed -e 's/^/    /' | tee -a $build_log

    # Save the rendered readme from the recipe file to a Markdown file
    if [[ -n "$README_J2" ]]; then
	readme_file=$(yq . $recipe_file | jq -r '.files[] | select(.purpose == "readme").name')
        echo "$(date +'%Y%m%d %H:%M:%S') generating readme file $readme_file" | tee -a $build_log
	yq . $recipe_file | jq -r '.files[] | select(.purpose == "readme").content' > "$readme_file"
        echo "$(date +'%Y%m%d %H:%M:%S') sha256 sum for the readme file is:" | tee -a $build_log
        sha256sum $readme_file | sed -e 's/^/    /' | tee -a $build_log
    fi

    echo "$(date +'%Y%m%d %H:%M:%S') starting container image builds" | tee -a $build_log

    while IFS= read -r line; do
        printf '%s [BUILD] %s\n' "$(date +'%Y%m%d %H:%M:%S')" "$line"
    done < <(scripts/build-images build "$recipe_file" "$build_dir" 2>&1) | tee -a $build_log

    echo "$(date +'%Y%m%d %H:%M:%S') container image builds completed" | tee -a $build_log
}

main "$@"
