#!/usr/bin/env python3

import argparse
import jinja2
import yaml


def main():
    # Define command line arguments
    parser = argparse.ArgumentParser(description='Render a Jinja2 template with variables from YAML files.')
    parser.add_argument('template_file', type=str, help='path to the Jinja2 template file')
    parser.add_argument('variable_files', type=str, nargs='+', help='list of paths to YAML files containing variables')

    # Parse command line arguments
    args = parser.parse_args()

    # Load YAML files into a single context dictionary
    context = {}
    for variable_file in args.variable_files:
        with open(variable_file, 'r') as yaml_file:
            context = {**context, **yaml.safe_load(yaml_file)}

    # Load Jinja2 template
    template_loader = jinja2.FileSystemLoader(searchpath='./')
    template_env = jinja2.Environment(loader=template_loader)
    template = template_env.get_template(args.template_file)

    # Render template with combined YAML file values
    rendered_template = template.render(context)

    # Print the rendered template
    print(rendered_template)


if __name__ == "__main__":
    main()
